version: "2"
networks:
  piholenet:
    ipam:
      driver: default
      config:
      - subnet: 10.1.0.0/24

services:
  pihole:
    container_name: pihole
    hostname: pihole
    image: pihole/pihole:2022.11.2
    shm_size: 4gb
    restart: always
    networks:
      piholenet:
        ipv4_address: 10.1.0.3
    ports:
      - "8080:80/tcp"
      - "443:443/tcp"
      - "53:53/udp"
      - "53:53/tcp"
    environment:
      TZ: "America/New York"
      PIHOLE_DNS_: "10.1.0.2"
      DNSSEC: "false"
      CUSTOM_CACHE_SIZE: "0"
      RATE_LIMIT: "0/0"
      WEBPASSWORD_FILE: "/webpass"
      DNSMASQ_USER: "root"
      PIHOLE_UID: "0"
    volumes:
      - /home/rob/pihole/.webpass:/webpass:ro
      - /home/rob/pihole/pihole:/etc/pihole:rw
      - /home/rob/pihole/dnsmasq/02-lan.conf:/etc/dnsmasq.d/02-lan.conf:ro

  unbound:
    container_name: unbound
    privileged: true
    build:
      context: .
      # Source https://github.com/MatthewVance/unbound-docker
      # They don't support ARM yet, so build it ourselves
      dockerfile: "Dockerfile.mvanceunbound"
    restart: always
    networks:
      piholenet:
        ipv4_address: 10.1.0.2
    environment:
      DNSMASQ_USER: "root"
    ports:
      - "53/udp"
      - "53/tcp"
      #- "5354:5354/udp"
      #- "5354:5354/tcp"
    volumes:
      - /home/rob/pihole/unboundconf/a-records.conf:/opt/unbound/etc/unbound/a-records.conf:ro
      - /home/rob/pihole/unboundconf/srv-records.conf:/opt/unbound/etc/unbound/srv-records.conf:ro
      - /home/rob/pihole/unboundconf/forward-records.conf:/opt/unbound/etc/unbound/forward-records.conf:ro
