FROM multiarch/debian-debootstrap:arm64-bullseye-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y \
    dnsutils \
    dns-root-data \
    lsof \
    unbound && \
    apt-get purge -y --auto-remove

ADD ./unbound-root.key /var/lib/unbound/root.key
ADD https://www.internic.net/domain/named.root /var/lib/unbound/root.hints
RUN chmod 644 /var/lib/unbound/root.hints

EXPOSE 5354/udp
EXPOSE 5354/tcp

ENTRYPOINT ["/usr/sbin/unbound", "-d"]
