FROM multiarch/debian-debootstrap:armhf-stretch-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y \
    dnsutils \
    unbound && \
    apt-get purge -y --auto-remove

ADD ./unbound-root.key /var/lib/unbound/root.key

ADD https://www.internic.net/domain/named.root /var/lib/unbound/root.hints
RUN chmod 644 /var/lib/unbound/root.hints

ENTRYPOINT ["/usr/sbin/unbound", "-d"]
