#!/bin/bash
### BEGIN INIT INFO
# Provides:          pihole
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     5
# Default-Stop:      0 1 6
# Short-Description: Starts pihole containers
# Description:       Starts pihole containers
### END INIT INFO
set -euo pipefail

PIHOME="/home/pi/pihole"

case "$1" in
start)
  cd "${PIHOME}"
  ./run.sh
  ./set_admin_password.sh
  ;;
stop)
  docker kill unbound
  docker kill pihole
  ;;
esac
