#!/bin/bash
### BEGIN INIT INFO
# Provides:          pihole
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     5
# Default-Stop:      0 1 6
# Short-Description: Starts pihole containers
# Description:       Starts pihole containers
### END INIT INFO
set -euo pipefail

case "$1" in
start)
	/home/pi/pihole/run.sh
	;;
stop)
	docker kill unbound
	docker kill pihole
	;;
esac
